blank_issues_enabled: true
contact_links:
  - name: Feature Requests
    url: https://github.com/acemod/ACE-Anvil/discussions/categories/feature-requests
    about: Please post feature requests in the pinned discussion.
